# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tapas/protos/negative_retrieval_examples.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tapas/protos/negative_retrieval_examples.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tapas.protos import interaction_pb2 as tapas_dot_protos_dot_interaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.tapas/protos/negative_retrieval_examples.proto\x12\x0elanguage.tapas\x1a\x1etapas/protos/interaction.proto\"\xc9\x01\n\x19NegativeRetrievalExamples\x12:\n\x08\x65xamples\x18\x01 \x03(\x0b\x32(.language.tapas.NegativeRetrievalExample2p\n\x1fnegative_retrieval_examples_ext\x12\x18.language.tapas.Question\x18\xd0\xab\xe0\x89\x01 \x01(\x0b\x32).language.tapas.NegativeRetrievalExamples\"\xcd\x01\n\x18NegativeRetrievalExample\x12$\n\x05table\x18\x01 \x01(\x0b\x32\x15.language.tapas.Table\x12;\n\x04type\x18\x02 \x01(\x0e\x32-.language.tapas.NegativeRetrievalExample.Type\x12\x0c\n\x04rank\x18\x03 \x01(\x05\x12\r\n\x05score\x18\x04 \x01(\x02\"1\n\x04Type\x12\x0c\n\x08\x42\x41SELINE\x10\x01\x12\x0c\n\x08\x44OCUMENT\x10\x02\x12\r\n\tCORRUPTED\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tapas.protos.negative_retrieval_examples_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEGATIVERETRIEVALEXAMPLES']._serialized_start=99
  _globals['_NEGATIVERETRIEVALEXAMPLES']._serialized_end=300
  _globals['_NEGATIVERETRIEVALEXAMPLE']._serialized_start=303
  _globals['_NEGATIVERETRIEVALEXAMPLE']._serialized_end=508
  _globals['_NEGATIVERETRIEVALEXAMPLE_TYPE']._serialized_start=459
  _globals['_NEGATIVERETRIEVALEXAMPLE_TYPE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
