# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tapas/protos/retriever_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# # # _runtime_version.ValidateProtobufRuntimeVersion(
# #     _runtime_version.Domain.PUBLIC,
# #     6,
# #     31,
# #     1,
# #     '',
# #     'tapas/protos/retriever_info.proto'
# )
# # @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tapas.protos import interaction_pb2 as tapas_dot_protos_dot_interaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!tapas/protos/retriever_info.proto\x12\x0elanguage.tapas\x1a\x1etapas/protos/interaction.proto\"\x7f\n\rRetrieverInfo\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\x32Q\n\x0cquestion_ext\x12\x18.language.tapas.Question\x18\xe0\xb8\xdd\xa0\x01 \x01(\x0b\x32\x1d.language.tapas.RetrieverInfo')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tapas.protos.retriever_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVERINFO']._serialized_start=85
  _globals['_RETRIEVERINFO']._serialized_end=212
# @@protoc_insertion_point(module_scope)
