# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tapas/protos/table_selection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
# from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# # # _runtime_version.ValidateProtobufRuntimeVersion(
# #     _runtime_version.Domain.PUBLIC,
# #     6,
# #     31,
# #     1,
# #     '',
# #     'tapas/protos/table_selection.proto'
# )
# # @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tapas.protos import interaction_pb2 as tapas_dot_protos_dot_interaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"tapas/protos/table_selection.proto\x12\x0elanguage.tapas\x1a\x1etapas/protos/interaction.proto\"\xe1\x07\n\x0eTableSelection\x12H\n\x0fselected_tokens\x18\x03 \x03(\x0b\x32/.language.tapas.TableSelection.TokenCoordinates\x12S\n\x16model_prediction_stats\x18\x02 \x01(\x0b\x32\x33.language.tapas.TableSelection.ModelPredictionStats\x12\x37\n\x05\x64\x65\x62ug\x18\x64 \x01(\x0b\x32(.language.tapas.TableSelection.DebugInfo\x1aP\n\x10TokenCoordinates\x12\x11\n\trow_index\x18\x01 \x01(\x05\x12\x14\n\x0c\x63olumn_index\x18\x02 \x01(\x05\x12\x13\n\x0btoken_index\x18\x03 \x01(\x05\x1a\x44\n\x1cModelPredictionStatsPerModel\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nis_correct\x18\x02 \x01(\x08\x1a\x8c\x01\n\x1dModelPredictionStatsPerColumn\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\x05\x12[\n\x16model_prediction_stats\x18\x02 \x03(\x0b\x32;.language.tapas.TableSelection.ModelPredictionStatsPerModel\x1a\xd2\x01\n\x14ModelPredictionStats\x12]\n\x17\x63olumn_prediction_stats\x18\x01 \x03(\x0b\x32<.language.tapas.TableSelection.ModelPredictionStatsPerColumn\x12[\n\x16model_prediction_stats\x18\x02 \x03(\x0b\x32;.language.tapas.TableSelection.ModelPredictionStatsPerModel\x1a\x9f\x01\n\tDebugInfo\x12@\n\x07\x63olumns\x18\x01 \x03(\x0b\x32/.language.tapas.TableSelection.DebugInfo.Column\x1aP\n\x06\x43olumn\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x13\n\x0bis_selected\x18\x03 \x01(\x08\x12\x13\n\x0bis_required\x18\x04 \x01(\x08\x32Y\n\x13table_selection_ext\x12\x18.language.tapas.Question\x18\xcf\xab\xe0\x89\x01 \x01(\x0b\x32\x1e.language.tapas.TableSelection')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tapas.protos.table_selection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TABLESELECTION']._serialized_start=87
  _globals['_TABLESELECTION']._serialized_end=1080
  _globals['_TABLESELECTION_TOKENCOORDINATES']._serialized_start=321
  _globals['_TABLESELECTION_TOKENCOORDINATES']._serialized_end=401
  _globals['_TABLESELECTION_MODELPREDICTIONSTATSPERMODEL']._serialized_start=403
  _globals['_TABLESELECTION_MODELPREDICTIONSTATSPERMODEL']._serialized_end=471
  _globals['_TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN']._serialized_start=474
  _globals['_TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN']._serialized_end=614
  _globals['_TABLESELECTION_MODELPREDICTIONSTATS']._serialized_start=617
  _globals['_TABLESELECTION_MODELPREDICTIONSTATS']._serialized_end=827
  _globals['_TABLESELECTION_DEBUGINFO']._serialized_start=830
  _globals['_TABLESELECTION_DEBUGINFO']._serialized_end=989
  _globals['_TABLESELECTION_DEBUGINFO_COLUMN']._serialized_start=909
  _globals['_TABLESELECTION_DEBUGINFO_COLUMN']._serialized_end=989
# @@protoc_insertion_point(module_scope)
