# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tapas/protos/table_pruning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tapas/protos/table_pruning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n tapas/protos/table_pruning.proto\x12\x0elanguage.tapas\"\xf7\x03\n\x04Loss\x12:\n\x0cunsupervised\x18\xc8\x01 \x01(\x0b\x32!.language.tapas.Loss.UnsupervisedH\x00\x12\x32\n\x05train\x18\x90\x03 \x01(\x0b\x32\".language.tapas.Loss.HardSelection\x12\x31\n\x04\x65val\x18\xf4\x03 \x01(\x0b\x32\".language.tapas.Loss.HardSelection\x12\'\n\x17\x61\x64\x64_classification_loss\x18\xd8\x04 \x01(\x08:\x05\x66\x61lse\x1a\x88\x01\n\rHardSelection\x12\x44\n\x0cselection_fn\x18\x01 \x01(\x0e\x32..language.tapas.Loss.HardSelection.SelectionFn\"1\n\x0bSelectionFn\x12\x07\n\x03\x41LL\x10\x00\x12\t\n\x05TOP_K\x10\x01\x12\x0e\n\nMASK_TOP_K\x10\x02\x1a\x8f\x01\n\x0cUnsupervised\x12H\n\x0eregularization\x18\x05 \x01(\x0e\x32\x30.language.tapas.Loss.Unsupervised.Regularization\"5\n\x0eRegularization\x12\x08\n\x04NONE\x10\x00\x12\x06\n\x02L1\x10\x01\x12\x06\n\x02L2\x10\x02\x12\t\n\x05L1_L2\x10\x03\x42\x06\n\x04loss\"`\n\x10\x41vgCosSimilarity\x12(\n\x19use_positional_embeddings\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\"\n\x04loss\x18\x03 \x01(\x0b\x32\x14.language.tapas.Loss\"\xeb\x01\n\x05TAPAS\x12\x32\n\tselection\x18\x02 \x01(\x0e\x32\x1f.language.tapas.TAPAS.Selection\x12\x18\n\x10\x62\x65rt_config_file\x18\x03 \x01(\t\x12\x1c\n\x14\x62\x65rt_init_checkpoint\x18\x04 \x01(\t\x12,\n\x1dreset_position_index_per_cell\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\"\n\x04loss\x18\x05 \x01(\x0b\x32\x14.language.tapas.Loss\"$\n\tSelection\x12\x0b\n\x07\x43OLUMNS\x10\x00\x12\n\n\x06TOKENS\x10\x01\"\r\n\x0b\x46irstTokens\"\xdf\x01\n\x11TablePruningModel\x12\x16\n\x0emax_num_tokens\x18\x01 \x01(\x05\x12>\n\x12\x61vg_cos_similarity\x18\x02 \x01(\x0b\x32 .language.tapas.AvgCosSimilarityH\x00\x12&\n\x05tapas\x18\x03 \x01(\x0b\x32\x15.language.tapas.TAPASH\x00\x12\x33\n\x0c\x66irst_tokens\x18\x04 \x01(\x0b\x32\x1b.language.tapas.FirstTokensH\x00\x42\x15\n\x13table_pruning_model')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tapas.protos.table_pruning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOSS']._serialized_start=53
  _globals['_LOSS']._serialized_end=556
  _globals['_LOSS_HARDSELECTION']._serialized_start=266
  _globals['_LOSS_HARDSELECTION']._serialized_end=402
  _globals['_LOSS_HARDSELECTION_SELECTIONFN']._serialized_start=353
  _globals['_LOSS_HARDSELECTION_SELECTIONFN']._serialized_end=402
  _globals['_LOSS_UNSUPERVISED']._serialized_start=405
  _globals['_LOSS_UNSUPERVISED']._serialized_end=548
  _globals['_LOSS_UNSUPERVISED_REGULARIZATION']._serialized_start=495
  _globals['_LOSS_UNSUPERVISED_REGULARIZATION']._serialized_end=548
  _globals['_AVGCOSSIMILARITY']._serialized_start=558
  _globals['_AVGCOSSIMILARITY']._serialized_end=654
  _globals['_TAPAS']._serialized_start=657
  _globals['_TAPAS']._serialized_end=892
  _globals['_TAPAS_SELECTION']._serialized_start=856
  _globals['_TAPAS_SELECTION']._serialized_end=892
  _globals['_FIRSTTOKENS']._serialized_start=894
  _globals['_FIRSTTOKENS']._serialized_end=907
  _globals['_TABLEPRUNINGMODEL']._serialized_start=910
  _globals['_TABLEPRUNINGMODEL']._serialized_end=1133
# @@protoc_insertion_point(module_scope)
